openapi: 3.0.0
info:
  title: VORTEX API
  description: API for the VORTEX stack application
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /:
    get:
      summary: Health check
      description: Returns a 200 OK status if the backend is healthy.
      responses:
        '200':
          description: Backend is healthy
          content:
            text/plain:
              schema:
                type: string
                example: Backend is healthy
